default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean bundleRelease")
    upload_to_play_store(
      track: 'production',
      aab: './app/build/outputs/bundle/release/app-release.aab'
    )
  end

  desc "Deploy to internal testing track"
  lane :internal do
    increment_version_code(
      gradle_file_path: "./app/build.gradle.kts"
    )

    increment_version_name(
      gradle_file_path: "./app/build.gradle.kts",
      bump_type: "patch"
    )
    gradle(task: "clean bundleRelease")
    upload_to_play_store(
      track: 'internal',
      aab: './app/build/outputs/bundle/release/app-release.aab',
      release_status: 'draft'
    )
  end

  desc "Deploy to alpha testing track"
  lane :alpha do
    gradle(task: "clean bundleRelease")
    upload_to_play_store(
      track: 'alpha',
      aab: './app/build/outputs/bundle/release/app-release.aab'
    )
  end

  desc "Deploy to beta testing track"
  lane :beta_play do
    gradle(task: "clean bundleRelease")
    upload_to_play_store(
      track: 'beta',
      aab: './app/build/outputs/bundle/release/app-release.aab'
    )
  end
end
